GENRES_TRANSLATION = {
    "אינדי": "Indie",
    "אינדי הודי": "Indian Independent",
    "אינדי-פופ": "Indie Pop",
    "אלטרנטיבית": "Alternative",
    "אלקטרוני": "Electronic",
    "אלקטרוניקה": "Electronica",
    "אלקטרונית": "Electronic",
    "אמריקנה": "Americana",
    "אנימה": "Anime",
    "אפריקאנס": "Afrikaans",
    "אקוסטי": "Acoustic",
    "אר אנד בי/מוסיקת נשמה": "R&B/Soul",
    "בהופעה": "Live",
    "בוליווד": "Bollywood",
    "ביילה פאנק": "Baile Funk",
    "בלוז": "Blues",
    "גוספל": "Gospel",
    "גיימינג": "Gaming",
    "ג׳אז": "Jazz",
    "דאב": "Dub",
    "דאנס": "Dance",
    "האוס": "Electronic",
    "היפ הופ": "Hip-Hop",
    "היפ-הופ יפני": "J-Hip-Hop",
    "היפ-הופ רוסי": "Russian Hip-Hop",
    "היפ-הופ/ראפ": "Hip-Hop/Rap",
    "זמר/פזמונאי": "Singer/Songwriter",
    "ים תיכוני": "Mizrahi Music",
    "יפן": "Japan",
    "ישן וטוב": "Oldies",
    "כושר גופני": "Fitness",
    "להיטים": "Hits",
    "לטינו": "Latino",
    "לכל המשפחה": "Kids & Family",
    "מוטיבציה": "Motivation",
    "מוסיקה": "Music",
    "מוסיקה אינדונזית": "Indonesian Music",
    "מוסיקה אפריקאית": "African Music",
    "מוסיקה בטלוגו": "Telugu",
    "מוסיקה בטמילית": "Tamil",
    "מוסיקה במליאלאם": "Malayalam",
    "מוסיקה בצרפתית": "Musique francophone",
    "מוסיקה בקאיוקיוקו": "Kayokyoku",
    "מוסיקה בקאנדה": "Kannada",
    "מוסיקה ברזילאית - Sertanejo": "Sertanejo",
    "מוסיקה דתית": "Religi/Ketuhanan",
    "מוסיקה הודית - Sanat": "Sanat",
    "מוסיקה טרופית": "Música Tropical",
    "מוסיקה ישראלית": "Israeli",
    "מוסיקה לטינית עכשווית": "Urbano Latino",
    "מוסיקה לנסיעה": "Commuting",
    "מוסיקה מלזית": "Malaysian Music",
    "מוסיקה מקסיקנית": "Música Mexicana",
    "מוסיקה מתאילנד": "Thai Music",
    "מוסיקה פופולרית מברזיל": "MPB",
    "מוסיקה פיליפינית מקורית": "Original Pilipino Music",
    "מוסיקה פנג׳אבית": "Punjabi",
    "מוסיקה קאריבית: ואיינאטו": "Vallenato",
    "מוסיקת עם טורקית": "Turkish Folk Music",
    "מטאל": "Metal",
    "מיקסים של DJ וסטים חיים": "DJ Mixes & Live Sets",
    "מסיבה": "Party",
    "מרחבי העולם": "Worldwide",
    "סמבה": "Samba",
    "ערבית": "Arabic",
    "פאנק": "Punk",
    "פאנק/נשמה": "Soul/Funk",
    "פולק": "Folk",
    "פולק-רוק": "Folk-Rock",
    "פופ": "Pop",
    "פופ איטלקי": "Pop Italiano",
    "פופ במנדרינית": "Mandopop",
    "פופ בספרדית": "Pop in Spanish",
    "פופ ברזילאי": "Brazilian Pop",
    "פופ גרמני": "Deutschpop",
    "פופ יפני": "J-Pop",
    "פופ לטיני": "Pop Latino",
    "פופ צרפתי": "French Pop",
    "פופ קוריאני": "K-Pop",
    "פופ רוסי": "Russian Pop",
    "פופ/רוק": "Pop/Rock",
    "פלמנקו": "Flamenco",
    "פסקול": "Soundtrack",
    "צ׳ילאאוט": "Chill",
    "קאנטרי": "Country",
    "קולנוע וטלוויזיה": "Film, TV & Stage",
    "קומדיה": "Comedy",
    "קלאסיקות": "Classics",
    "קלאסית": "Classical",
    "קנדית": "Canadian",
    "ראפ": "Rap",
    "ראפ גרמני": "Deutschrap",
    "ראפ צרפתי": "French Rap",
    "רגאיי": "Reggae",
    "רווחה נפשית": "Wellness",
    "רומנטיקה": "Romance",
    "רוסית": "Russian",
    "רוק": "Rock",
    "רוק בספרדית": "Rock in Spanish",
    "רוק ואלטרנטיבית בספרדית": "Rock y Alternativo",
    "רוק יפני": "J-Rock",
    "רוק כבד": "Hard Rock",
    "רוק קלאסי": "Classic Rock",
    "רוק רוסי": "Russian Rock",
    "ריכוז": "Focus",
    "שינה": "Sleep",
    "שלאגר": "Schlager",
    "שנות ה-60": "’60s",
    "שנות ה-70": "’70s",
    "שנות ה-80": "’80s",
    "שנות ה-90": "’90s",
    "שנות ה‑2000": "2000s",
    "שנות ה‑2010": "2010s",
    "תחושה טובה": "Feel Good",
    "תחושת עצבות": "Feeling Blue"
}
